name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  minor:
    labels:
      - 'breaking-change'
  default: patch
categories:
  - title: 'âš ï¸ Breaking changes'
    label: 'breaking-change'
  - title: 'ğŸš€ Enhancements'
    label: 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    label: 'bug'
template: |
  $CHANGES
  Thanks again to $CONTRIBUTORS! ğŸ‰
